"""Hero and enemy catalogue.

Each entry is DATA, not drawing code - the rig turns a look plus a set of
joint angles into five animations. Adding a character is one dict.
"""

from rig import Body, C

# ---------------------------------------------------------------------------
#  HEROES  -  10 playable classes
# ---------------------------------------------------------------------------

HEROES = [
    dict(name="warrior", label="Warrior", role="Tank / melee bruiser",
         blurb="Sword and board. High HP, taunts, soaks the front rank.",
         body=Body(cloth=C("4d8fd6"), accent=C("e0c46c"), helmet="dome",
                   torso="plate", weapon="sword", offhand="shield",
                   build=1.1)),
    dict(name="paladin", label="Paladin", role="Tank / support",
         blurb="Holy warhammer and consecrated shield. Heals on smite.",
         body=Body(cloth=C("e8e4dc"), accent=C("e0c46c"), helmet="plume",
                   torso="plate", weapon="hammer", offhand="shield",
                   cape=C("d4b04a"), extras=("cloak", "shoulderpads"),
                   build=1.12)),
    dict(name="ranger", label="Ranger", role="Ranged DPS",
         blurb="Longbow, high crit, opens every fight from the back rank.",
         body=Body(cloth=C("4f7530"), accent=C("8a5f38"), helmet="hood",
                   torso="tunic", weapon="bow", build=0.95)),
    dict(name="rogue", label="Rogue", role="Burst DPS",
         blurb="Twin daggers and poison. Massive damage from stealth.",
         body=Body(cloth=C("3f3a52"), accent=C("8ad148"), helmet="hood",
                   torso="tunic", weapon="dagger", offhand="dagger",
                   build=0.9, scale=0.96)),
    dict(name="mage", label="Mage", role="Magic DPS",
         blurb="Arcane staff. Hits every enemy, folds if anything reaches her.",
         body=Body(cloth=C("8e5bc4"), accent=C("f2d05a"), helmet="wizard",
                   torso="robe", weapon="staff", build=0.88, scale=0.97)),
    dict(name="cleric", label="Cleric", role="Healer",
         blurb="Restores the party and shrugs off curses. Mace for emergencies.",
         body=Body(cloth=C("e8e4dc"), accent=C("53c1a6"), helmet="band",
                   torso="robe", weapon="mace", build=0.92)),
    dict(name="berserker", label="Berserker", role="Melee DPS",
         blurb="Greataxe, no armour. Damage scales as his HP drops.",
         body=Body(cloth=C("b3543f"), accent=C("ded6c0"), helmet="horned",
                   torso="fur", weapon="greataxe", build=1.2, scale=1.08,
                   skin=C("e0ab86"))),
    dict(name="monk", label="Monk", role="Melee / evasion",
         blurb="Iron claws and footwork. Dodges, then counters twice.",
         body=Body(cloth=C("d97b3c"), accent=C("e8e4dc"), helmet="band",
                   torso="bare", weapon="claw", offhand="claw", build=1.0)),
    dict(name="necromancer", label="Necromancer", role="Summoner",
         blurb="Raises the fallen. Every corpse on the field is a resource.",
         body=Body(cloth=C("2f4038"), accent=C("8ad148"), helmet="hood",
                   torso="robe", weapon="scythe", extras=("aura",),
                   skin=C("c9c3ad"), eyes=C("8ad148"), build=0.9)),
    dict(name="templar", label="Templar", role="Frontline DPS",
         blurb="Two-handed greatsword. Slow, enormous, cleaves the whole row.",
         body=Body(cloth=C("c9ccd6"), accent=C("e0c46c"), helmet="visor",
                   torso="plate", weapon="greatsword", cape=C("9e2f2f"),
                   extras=("cloak", "shoulderpads"), build=1.15, scale=1.06)),
]

# ---------------------------------------------------------------------------
#  ENEMIES  -  28, in three tiers
# ---------------------------------------------------------------------------

def E(name, label, tier, blurb, body, **kw):
    return dict(name=name, label=label, tier=tier, blurb=blurb, body=body, **kw)


ENEMIES = [
    # -- tier 1: fodder ----------------------------------------------------
    E("goblin_grunt", "Goblin Grunt", 1, "Cowardly, numerous, hits in packs.",
      Body(skin=C("7dae4c"), cloth=C("6b4a32"), head="goblin", torso="tunic",
           weapon="club", build=0.85, scale=0.88)),
    E("goblin_archer", "Goblin Archer", 1, "Stays at the back and plinks.",
      Body(skin=C("8fbc57"), cloth=C("4f7530"), head="goblin", torso="tunic",
           weapon="bow", build=0.82, scale=0.88)),
    E("goblin_shaman", "Goblin Shaman", 1, "Curses and weak hexes.",
      Body(skin=C("6f9e44"), cloth=C("8e5bc4"), head="goblin", torso="robe",
           weapon="wand", accent=C("f2d05a"), extras=("aura",),
           build=0.8, scale=0.88)),
    E("kobold", "Kobold", 1, "Trap-setter. Fragile but fast.",
      Body(skin=C("c07a4a"), cloth=C("8a4a32"), head="beast", torso="tunic",
           weapon="dagger", build=0.8, scale=0.82)),
    E("giant_rat", "Giant Rat", 1, "Diseased bite, swarms in numbers.",
      Body(skin=C("8a7f72"), cloth=C("6b625a"), head="beast", torso="fur",
           weapon="claw", extras=("tail",), build=0.9, scale=0.78)),
    E("bat", "Cave Bat", 1, "Erratic flyer, drains a little life.",
      Body(skin=C("5a4a63"), cloth=C("463a52"), head="beast", torso="fur",
           weapon="claw", extras=("batwings",), build=0.75, scale=0.72)),
    E("slime", "Green Slime", 1, "Splits when struck. Corrodes weapons.",
      Body(skin=C("8ad148"), cloth=C("6aa834"), head="slime", torso="bare",
           limb=C("8ad148"), build=1.05, scale=0.78)),
    E("skeleton", "Skeleton", 1, "Reassembles unless the skull is broken.",
      Body(skin=C("ded6c0"), cloth=C("9a917c"), head="skull", torso="ribs",
           weapon="sword", limb=C("ded6c0"), build=0.85)),

    # -- tier 2: regulars --------------------------------------------------
    E("skeleton_archer", "Bone Archer", 2, "Fires splintered arrows.",
      Body(skin=C("ded6c0"), cloth=C("9a917c"), head="skull", torso="ribs",
           weapon="bow", limb=C("ded6c0"), build=0.85)),
    E("zombie", "Zombie", 2, "Slow, relentless, infects on hit.",
      Body(skin=C("8fa878"), cloth=C("5c5548"), head="undead", torso="tunic",
           weapon="claw", eyes=C("8ad148"), build=1.0)),
    E("ghoul", "Ghoul", 2, "Leaps the back line and feeds.",
      Body(skin=C("b6b39a"), cloth=C("4a4438"), head="undead", torso="bare",
           weapon="claw", offhand="claw", eyes=C("c4453a"), build=0.9)),
    E("bandit", "Bandit", 2, "Steals gold on a successful hit.",
      Body(skin=C("d9a077"), cloth=C("6b4a32"), head="human", helmet="band",
           torso="tunic", weapon="sword", accent=C("c4453a"))),
    E("cultist", "Cultist", 2, "Sacrifices allies to empower itself.",
      Body(skin=C("c9a98c"), cloth=C("6b2f4a"), head="human", helmet="hood",
           torso="robe", weapon="dagger", accent=C("f2d05a"), build=0.9)),
    E("orc_brute", "Orc Brute", 2, "Big swing, big opening.",
      Body(skin=C("5c8f4a"), cloth=C("4a3222"), head="goblin", torso="fur",
           weapon="club", build=1.25, scale=1.1)),
    E("dire_wolf", "Dire Wolf", 2, "Pack hunter, always strikes first.",
      Body(skin=C("6b6157"), cloth=C("554d45"),
           head="beast", torso="fur", weapon="claw",
           extras=("tail",), build=1.05, scale=0.9)),
    E("giant_spider", "Giant Spider", 2, "Webs a target, then poisons it.",
      Body(skin=C("3f3a52"), cloth=C("2e2a3d"), head="insect",
           torso="carapace", weapon="claw", eyes=C("c4453a"),
           extras=("spikes",), build=1.1, scale=0.85)),
    E("scorpion", "Sand Scorpion", 2, "Stinger applies stacking poison.",
      Body(skin=C("c9a04a"), cloth=C("a37f34"), head="insect",
           torso="carapace", weapon="claw", offhand="claw",
           extras=("tail",), build=1.05, scale=0.88)),
    E("harpy", "Harpy", 2, "Screeches, stuns, and dives.",
      Body(skin=C("d9a077"), cloth=C("b3543f"), head="bird", torso="fur",
           weapon="claw", accent=C("e0c46c"), extras=("wings",),
           build=0.9, scale=0.95)),
    E("imp", "Imp", 2, "Flings fire from out of reach.",
      Body(skin=C("c4453a"), cloth=C("8a2f28"), head="demon", torso="bare",
           weapon="wand", accent=C("f2d05a"), eyes=C("f2d05a"),
           extras=("batwings", "tail"), build=0.8, scale=0.78)),
    E("gargoyle", "Gargoyle", 2, "Stone skin. Immune until it animates.",
      Body(skin=C("8a8f9c"), cloth=C("6b7078"), head="demon", torso="carapace",
           weapon="claw", limb=C("8a8f9c"), eyes=C("f2d05a"),
           extras=("batwings", "spikes"), build=1.1, scale=1.0)),
    E("treant", "Treant", 2, "Roots the party in place. Weak to fire.",
      Body(skin=C("6b5238"), cloth=C("4f7530"), head="plant", torso="scales",
           weapon="club", accent=C("8ad148"), limb=C("6b5238"),
           build=1.25, scale=1.12)),
    E("mimic", "Mimic", 2, "Looks exactly like the chest you wanted.",
      Body(skin=C("8a5f38"), cloth=C("6b4a32"), head="slime", torso="bare",
           weapon="claw", accent=C("e0c46c"), eyes=C("c4453a"),
           limb=C("8a5f38"), build=1.15, scale=0.8)),

    # -- tier 3: elites and bosses ----------------------------------------
    E("orc_warchief", "Orc Warchief", 3, "Rallies every orc on the field.",
      Body(skin=C("4f7530"), cloth=C("3a5f30"), head="goblin", helmet="horned",
           torso="plate", weapon="greataxe", accent=C("c4453a"),
           extras=("shoulderpads",), build=1.28, scale=1.14)),
    E("skeleton_knight", "Bone Knight", 3, "Armoured undead. Parries.",
      Body(skin=C("ded6c0"), cloth=C("6b7078"), head="skull", helmet="visor",
           torso="plate", weapon="greatsword", limb=C("ded6c0"),
           eyes=C("c4453a"), cape=C("4a2f3f"), extras=("cloak",),
           build=1.12, scale=1.05)),
    E("wraith", "Wraith", 3, "Ignores armour entirely.",
      Body(skin=C("9fb0c4"), cloth=C("2e3444"), head="skull", helmet="hood",
           torso="robe", weapon="scythe", eyes=C("6fa8dc"),
           limb=C("9fb0c4"), extras=("aura",), build=0.95, scale=1.02)),
    E("minotaur", "Minotaur", 3, "Charges through the entire front rank.",
      Body(skin=C("7a4f32"), cloth=C("5e3f24"), head="beast", helmet="antlers",
           torso="fur", weapon="greataxe", accent=C("c4453a"),
           extras=("shoulderpads",), build=1.3, scale=1.16)),
    E("demon_lord", "Demon Lord", 3, "Summons imps and burns the ground.",
      Body(skin=C("9e2f2f"), cloth=C("3d1620"), head="demon", helmet="crown",
           torso="plate", weapon="trident", accent=C("f2d05a"),
           eyes=C("f2d05a"), cape=C("6b1f28"),
           extras=("batwings", "cloak", "flame"), build=1.25, scale=1.14)),
    E("lich", "Lich King", 3, "Resurrects itself once. Kill it twice.",
      Body(skin=C("c9c3ad"), cloth=C("2f4038"), head="skull", helmet="crown",
           torso="robe", weapon="staff", accent=C("8ad148"),
           eyes=C("8ad148"), extras=("aura", "cloak"),
           cape=C("1f2b26"), build=1.0, scale=1.05)),
    E("beholder", "Gaze Tyrant", 3, "Every eye fires a different curse.",
      Body(skin=C("8e5bc4"), cloth=C("6b3fa0"), head="eye", torso="bare",
           weapon=None, accent=C("f2d05a"), limb=C("8e5bc4"),
           extras=("aura", "spikes"), build=1.2, scale=0.95)),
]

TIER_NAMES = {1: "fodder", 2: "regular", 3: "elite"}
